### ISSUE TITLE
Error: Maximum redirections reached

### ISSUE THREAD

**Issue by Tyf0x** [auth0/auth0-authorization-extension#246]
Hi,

we currently cannot display the authorization configuration page without being presented with a JSON error message:
`{"error":"Error: Maximum redirections reached\n at ClientRequest.onResponse (/data/node_modules/wreck/lib/index.js:222:36)\n at Object.onceWrapper (events.js:315:30)\n at emitOne (events.js:116:13)\n at ClientRequest.emit (events.js:211:7)\n at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:558:21)\n at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)\n at Socket.socketOnData (_http_client.js:454:20)\n at emitOne (events.js:116:13)\n at Socket.emit (events.js:211:7)\n at addChunk (_stream_readable.js:263:12)\n at readableAddChunk (_stream_readable.js:250:11)\n at Socket.Readable.push (_stream_readable.js:208:10)\n at Pipe.onread (net.js:601:20)"}`

This is preventing us to configure new groups or assign users to them.
This also seems to break our software sign-in process for new users (it seems that the authorisation data is not sent through).

This has a major impact on all our tenants, including production.

Can you please advise on the best course of action?

[auth0 forums discussion](https://community.auth0.com/t/authorization-extension-error-maximum-redirections-reached/20060)

Thanks

**Comment by Tyf0x** [comment]
Fixed by Auth0 (cf. forum link above)
