### ISSUE TITLE
Error in Authorization Extension if Group Mappings exist

### ISSUE THREAD

**Issue by pushpabrol** [auth0/auth0-authorization-extension#6]
I have a group in the authorization extension with just one group mappings- i.e. A windows azure AD connection and a group.

The authorization extension errors out with the following error on every execution. A customer has also raised this issue and is a priority now. Please let me know if you need more information on steps to repo.

2016-07-31T00:27:43.039Z - error:  TypeError: Cannot read property 'members' of undefined
        at /data/auth0-authz-1.4.js:1:16552
        at arrayEach (/data/node_modules/lodash/index.js:1289:13)
        at Function.<anonymous> (/data/node_modules/lodash/index.js:3345:13)
        at /data/auth0-authz-1.4.js:1:16447
        at arrayEach (/data/node_modules/lodash/index.js:1289:13)
        at Function.<anonymous> (/data/node_modules/lodash/index.js:3345:13)
        at /data/auth0-authz-1.4.js:1:16374
        at tryCatcher (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/util.js:24:31)
        at Promise._settlePromiseFromHandler (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/promise.js:454:31)
        at Promise._settlePromiseAt (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/promise.js:530:18)
        at Promise._settlePromiseAtPostResolution (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/promise.js:224:10)
        at bound (domain.js:287:14)
        at Promise.runBound (domain.js:300:12)
        at Async._drainQueue (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/async.js:182:12)
        at Async._drainQueues (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/async.js:187:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/data/_verquire/mongoose/4.1.6/node_modules/mongoose/node_modules/mquery/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:383:17)
[00:28:51.463Z]  INFO wt: finished webtask request 1469924861447.804533 with HTTP 500 in 1596ms
[00:28:51.465Z]  INFO wt: 2016-07-31T00:27:43.045Z - info: POST /api/run/pushp/adf6e2f2b84784b57522e3b19dfc9201/api/authorize/waad%7Cwt6mnFMVA264M7RvrmXH4L95GGkJCJBjawRlTufFjlU 500 112.585 ms - 57
[00:28:51.481Z]  INFO wt: Access Denied: { message: 'Cannot read property \'members\' of undefined' }

**Comment by sandrinodimattia** [comment]
Solved in release 1.4.3
